# Generated by Django 4.1.3 on 2023-01-10 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estoques',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codproduto', models.TextField(default=None, max_length=10)),
                ('destaque', models.BooleanField(default=False)),
                ('saldo', models.IntegerField(default=0, null=True)),
            ],
        ),
    ]
