# Generated by Django 4.1.3 on 2023-01-10 23:50

from django.db import migrations, models
import produtos.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codproduto', models.TextField(default=None, max_length=10)),
                ('nome', models.TextField(default=None, max_length=100)),
                ('descricao', models.TextField(default=None, max_length=100)),
                ('preco', models.FloatField(default=None, max_length=100)),
                ('codtabela', models.TextField(default=None, max_length=2)),
                ('imagem', models.ImageField(blank=True, null=True, upload_to=produtos.models.upload_imagem_produto)),
                ('destaque', models.BooleanField(default=False)),
                ('ft_venda', models.IntegerField(default=1, null=True)),
                ('unidade', models.TextField(max_length=2, null=True)),
                ('uni_master', models.TextField(max_length=2, null=True)),
            ],
        ),
    ]
