# Generated by Django 4.1.3 on 2023-01-13 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pedidos_model',
            fields=[
                ('codpedido', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('cliente', models.TextField(default=None, max_length=10)),
                ('codpagamento', models.TextField(default=None, max_length=10)),
                ('valor_total', models.FloatField(default=None, max_length=10)),
                ('codtabela', models.TextField(default=None, max_length=2)),
                ('prazo', models.TextField(max_length=10, null=True)),
                ('rca', models.TextField(default=None, max_length=10)),
                ('status', models.IntegerField(default=0)),
                ('processado', models.BooleanField(default=False)),
                ('date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
