# Generated by Django 4.1.3 on 2023-01-13 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0004_remove_pedidos_model_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidos_model',
            name='codpedido',
            field=models.TextField(auto_created=True, primary_key=True, serialize=False),
        ),
    ]
