# Generated by Django 4.1.3 on 2023-01-13 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0006_alter_pedidos_model_codpedido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidos_model',
            name='codpedido',
            field=models.BigIntegerField(auto_created=True, primary_key=True, serialize=False),
        ),
    ]
