# Generated by Django 4.1.3 on 2023-01-15 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0012_alter_pedidos_model_codpedido'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pedidos_model',
            old_name='valor_total',
            new_name='valortotal',
        ),
    ]
