# Generated by Django 4.1.3 on 2023-01-16 00:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0013_rename_valor_total_pedidos_model_valortotal'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pedidos_model',
            old_name='valortotal',
            new_name='valor_total',
        ),
    ]
