# Generated by Django 4.1.3 on 2023-01-16 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos_item', '0012_remove_itempedidos_codpedido'),
        ('pedidos', '0015_rename_valor_total_pedidos_model_valortotal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidos_model',
            name='itemvalor',
            field=models.ManyToManyField(to='pedidos_item.itempedidos'),
        ),
    ]
