# Generated by Django 4.1.3 on 2023-01-16 01:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0016_alter_pedidos_model_itemvalor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedidos_model',
            name='itemvalor',
        ),
    ]
