# Generated by Django 4.1.3 on 2023-01-13 14:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pedidos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item_pedidos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codproduto', models.TextField(default=None, max_length=10)),
                ('item_valor', models.FloatField(blank=True, null=True)),
                ('item_quantidade', models.IntegerField(blank=True, null=True)),
                ('numseq', models.IntegerField(blank=True, null=True)),
                ('date', models.DateTimeField(auto_now=True)),
                ('status', models.TextField(default=None, max_length=1)),
                ('codpedido', models.ForeignKey(default=None, max_length=10, on_delete=django.db.models.deletion.CASCADE, to='pedidos.pedidos_model')),
            ],
        ),
    ]
