# Generated by Django 4.1.3 on 2023-01-13 14:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0004_remove_pedidos_model_date'),
        ('pedidos_item', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item_pedidos',
            name='codpedido',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='pedidos.pedidos_model'),
        ),
    ]
