# Generated by Django 4.1.3 on 2023-01-13 16:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0005_alter_pedidos_model_codpedido'),
        ('pedidos_item', '0002_alter_item_pedidos_codpedido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item_pedidos',
            name='codpedido',
            field=models.ForeignKey(default=None, max_length=10, on_delete=django.db.models.deletion.CASCADE, to='pedidos.pedidos_model'),
        ),
        migrations.AlterField(
            model_name='item_pedidos',
            name='codproduto',
            field=models.TextField(default=None, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='item_pedidos',
            name='item_valor',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
