# Generated by Django 4.1.3 on 2023-01-13 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos_item', '0003_alter_item_pedidos_codpedido_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item_pedidos',
            name='item_valor',
            field=models.FloatField(null=True),
        ),
    ]
