# Generated by Django 4.1.3 on 2023-01-14 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos_item', '0006_alter_item_pedidos_codpedido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item_pedidos',
            name='item_valor',
            field=models.FloatField(blank=True, default=1),
            preserve_default=False,
        ),
    ]
