# Generated by Django 4.1.3 on 2023-01-15 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos_item', '0007_alter_item_pedidos_item_valor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item_pedidos',
            old_name='item_quantidade',
            new_name='itemquantidade',
        ),
        migrations.RenameField(
            model_name='item_pedidos',
            old_name='item_valor',
            new_name='itemvalor',
        ),
    ]
