# Generated by Django 4.1.3 on 2023-01-16 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0013_rename_valor_total_pedidos_model_valortotal'),
        ('pedidos_item', '0009_rename_item_pedidos_itempedidos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itempedidos',
            name='itemvalor',
        ),
        migrations.AddField(
            model_name='itempedidos',
            name='itemvalor',
            field=models.ManyToManyField(related_name='itemvalor', to='pedidos.pedidos_model'),
        ),
    ]
