# Generated by Django 4.1.3 on 2023-01-16 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos_item', '0010_remove_itempedidos_itemvalor_itempedidos_itemvalor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itempedidos',
            name='itemvalor',
        ),
        migrations.AddField(
            model_name='itempedidos',
            name='itemvalor',
            field=models.FloatField(blank=True, default=1),
            preserve_default=False,
        ),
    ]
