# Generated by Django 4.1.3 on 2023-01-16 00:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos_item', '0011_remove_itempedidos_itemvalor_itempedidos_itemvalor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itempedidos',
            name='codpedido',
        ),
    ]
