# Generated by Django 4.1.3 on 2023-01-16 01:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0017_remove_pedidos_model_itemvalor'),
        ('pedidos_item', '0012_remove_itempedidos_codpedido'),
    ]

    operations = [
        migrations.AddField(
            model_name='itempedidos',
            name='codpedido',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='pedidos.pedidos_model'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='itempedidos',
            name='codproduto',
            field=models.TextField(default=None, max_length=10),
        ),
        migrations.AlterField(
            model_name='itempedidos',
            name='itemquantidade',
            field=models.IntegerField(blank=True, default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='itempedidos',
            name='numseq',
            field=models.IntegerField(blank=True, default=1),
            preserve_default=False,
        ),
    ]
