# Generated by Django 4.1.3 on 2023-01-10 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Metas_gestores',
            fields=[
                ('cod_equipe', models.TextField(default=None, max_length=10, primary_key=True, serialize=False)),
                ('nome_equipe', models.TextField(default=None, max_length=50)),
                ('meta_equipe', models.FloatField(default=None, max_length=12)),
                ('meta_master', models.FloatField(default=None, max_length=12)),
                ('meta_forn', models.FloatField(default=None, max_length=12)),
                ('cod_superv', models.IntegerField(default=None)),
            ],
        ),
    ]
