# Generated by Django 4.1.3 on 2023-01-10 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Destaque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codproduto', models.TextField()),
                ('nome', models.TextField()),
                ('descricao', models.TextField()),
                ('preco', models.FloatField()),
                ('codtabela', models.TextField()),
                ('imagem', models.ImageField(upload_to='')),
                ('destaque', models.BooleanField()),
                ('ft_venda', models.IntegerField()),
                ('unidade', models.TextField()),
                ('uni_master', models.TextField()),
            ],
            options={
                'db_table': 'destaque_page',
                'managed': False,
            },
        ),
    ]
