# Generated by Django 4.1.3 on 2023-01-10 23:50

import banner.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('cod_banner', models.TextField(default=None, max_length=10, primary_key=True, serialize=False)),
                ('nome_banner', models.TextField(default=None, max_length=100)),
                ('descricao_banner', models.TextField(default=None, max_length=100)),
                ('image_banner', models.ImageField(blank=True, null=True, upload_to=banner.models.upload_imagem_banner)),
            ],
        ),
    ]
